name: Deploy DevQuiz to Heroku
on:
  push:
    branches:
      - main
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      -name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: fronend-build
          path: fronend/build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - uses: actions/dowload-artifact@v2
        with:
          name: fronend-build
          path: backend/src/main/ressources/static
      - name: Build with maven
        run: maven -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: app-jar
          path: backend/target/app.jar


  deploy-heroku:
    runs-on: ubuntu-latest
    needs: build-backend
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: app.jar
          path: backend/target
      - name: Login to Heroku
        run: heroku container:login
      - name: Push Docker Container
        run: heroku container:push web -a fancy-dev-quiz
      - name: Deploy
        run: heroku container:release web -a fancy-dev-quiz